### ISSUE TITLE
Self destruct processes

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/page-metadata-service#104]
We should self destruct a process in either

1) after a specified timeout (1 hour)
2) if parsing fails

This will ensure that we do not accidentally leak sensitive information in the memory state of a process.

**Comment by jaredkerim** [comment]
This will be handled by ops using upstart automation as that is a simpler and more reliable approach than attempting to raise process.exit() within a timeout.

**Comment by jvehent** [comment]
jbuck: do you have a tracker for this?

**Comment by jbuck** [comment]
I put a link to the implementation in the bugzilla ticket
