### ISSUE TITLE
Fathom proxy is truncating descriptions

### ISSUE THREAD

**Issue by pdehaan** [mozilla/page-metadata-service#29]
Using my [crappy proxy diff tool](https://github.com/pdehaan/scraper-diff), it looks like we're possibly truncating the returned `description` (at 160 chars):

``` sh
node index --url "https://techcrunch.com/2016/08/10/new-macbook-pro-with-touch-id-sensor-and-oled-mini-screen-is-coming-soon/"

https://techcrunch.com/2016/08/10/new-macbook-pro-with-touch-id-sensor-and-oled-mini-screen-is-coming-soon/:
  description:
    embedly: Get ready for a massive MacBook Pro update. Apple is planning to unveil new 13-inch and 15-inch MacBook Pro laptops with retina displays soon. According to a new report from Bloomberg's Mark Gurman, Apple is building a completely new pro laptop with many new features, such as a Touch ID sensor and an OLED mini screen above the keyboard.
    fathom:  Get ready for a massive MacBook Pro update. Apple is planning to unveil new 13-inch and 15-inch MacBook Pro laptops with retina displays soon. According to a..
```

> Get ready for a massive MacBook Pro update. Apple is planning to unveil new 13-inch and 15-inch MacBook Pro laptops with retina displays soon. According to a..

Not sure if that makes sense to truncate from a Fathom or proxy standpoint, or if we should let the service _consumers_ decide where they want to truncate.

**Comment by jaredkerim** [comment]
On that page, the og:description tag says:

<meta property="og:description" content="Get ready for a massive MacBook Pro update. Apple is planning to unveil new 13-inch and 15-inch MacBook Pro laptops with retina displays soon. According to a.." />

They truncated it.  The page-metadata-parser should always return exactly what is contained in the content of a metadata tag.

**Comment by jaredkerim** [comment]
Actually I'm going to reopen this to discuss how we prioritize the content of fields.  On this example page, there are multiple metatags which expose a description, one of which is truncated by others are not, for example:

property="og:description" content="Get ready for a massive MacBook Pro update. Apple is planning to unveil new 13-inch and 15-inch MacBook Pro laptops with retina displays soon. According to a.."

name='twitter:description' content='Get ready for a massive MacBook Pro update. Apple is planning to unveil new 13-inch and 15-inch MacBook Pro laptops with retina displays soon. According to a new report from Bloomberg’s Mark&hellip;'

class="swiftype" name="excerpt" data-type="text" content="Get ready for a massive MacBook Pro update. Apple is planning to unveil new 13-inch and 15-inch MacBook Pro laptops with retina displays soon. According to a new report from Bloomberg’s Mark Gurman, Apple is building a completely new pro laptop with many new features, such as a Touch ID sensor and an OLED mini screen above the keyboard.
If you’ve been following MacBook Pro rumors, you know&hellip;"

**Comment by pdehaan** [comment]
And even the `<meta>` description is truncated:

```html
<meta name="description" content="Get ready for a massive MacBook Pro update. Apple is planning to unveil new 13-inch and 15-inch MacBook Pro laptops with retina displays soon. According to a..">
```
