### ISSUE TITLE
Add docker-flow routes

### ISSUE THREAD

**Issue by pdehaan** [mozilla/page-metadata-service#31]
https://metadata.dev.mozaws.net/__version__ currently barfs with this 💎 :

> Cannot GET /\_\_version\_\_

---

Whereas the Embedly proxy server gives me a glorious JSON blob of blobby greatness (which lets me get a rough "age" of the server and know what's deployed).

BEHOLD! https://embedly-proxy.services.mozilla.com/__version__:

```js
{
    commit: "946db90208fb8dc77f0e2313e48e4d310e0e4f95",
    version: "0.12",
    source: "https://github.com/mozilla/embedly-proxy.git"
}
```

**Comment by jaredkerim** [comment]
We should add all the docker-flow endpoints defined here:

https://github.com/mozilla-services/Dockerflow
