### ISSUE TITLE
Add redis caching

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/page-metadata-service#48]
Cache the metadata for a url in redis

**Comment by pdehaan** [comment]
FWIW, I think embedly generally caches results for 24h:

> `cache_age`: How long Embedly is going to cache the response for? Generally, this is for a day, unless some external factor tells us to reevaluate the resource.
>
> &mdash; via http://docs.embed.ly/docs/extract#response-attributes

**Comment by jaredkerim** [comment]
This is handled by https://github.com/mozilla/embedly-proxy
