### ISSUE TITLE
Add statsd support

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/page-metadata-service#53]
We should capture timing and event information to track the performance of this service.

**Comment by pdehaan** [comment]
I think this was resolved by the awkwardly titled https://github.com/mozilla/page-metadata-service/pull/63

**Comment by jaredkerim** [comment]
@pdehaan that was a gitfu misfire.

**Comment by pdehaan** [comment]
I was subtly implying we can close this meow.
It would appear I have no GitHub permissions to close/edit issues in this repo.
