### ISSUE TITLE
Spin up a prod stack server for add-on experiment

### ISSUE THREAD

**Issue by edmoz** [mozilla/page-metadata-service#56]

**Comment by edmoz** [comment]
update: in triage jared is done with most coding and ready for Ops to begin with stack config setup.

**Comment by edmoz** [comment]
@jaredkerim and updates here on if prod stack is live and @pdehaan can help test?

**Comment by pdehaan** [comment]
IRC update was:

> **jkerim**> **edwong**: deploying stage stack now, prod stack to follow!

**Comment by edmoz** [comment]
@jaredkerim any updates here - do we have a prod and stage endpoints to try out?

**Comment by jaredkerim** [comment]
@edmoz the stage stack is currently being deployed.  Once that is verified we will do the prod stack.

**Comment by edmoz** [comment]
prod is live, closing this: https://page-metadata.services.mozilla.com
