### ISSUE TITLE
Use Node Cluster to fork requests to child processes

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/page-metadata-service#99]
We should use a cluster/fork architecture to isolate the handling of individual requests.  This allows us to more effectively distribute workload which improves resource utilization and performance.  It also moves the processing of individual requests into isolated memory spaces to reduce the likelihood of memory scraping/injection compromising the data of other requesting parties.

See:

https://nodejs.org/api/cluster.html

**Comment by jaredkerim** [comment]
Theoretically we could self destruct a process if it fails to process catastrophically.  We could also add a timer to self destruct the process after a given timeout to ensure that we flush its memory state regularly.
